# ./configs/configs.yaml
training:
  batch_size: 128
  learning_rate: 0.0001
  num_epochs: 500
  weight_decay: 0.01
  grad_clip: 5.0
model:
  dropout_rate: 0.1
  num_classes: 20
paths:
  annotation: /home/djs/Python/mlcl/data/headgear/headgear.csv
  model_save_path: ./model/resnet50.pth
  dataset_path: /home/djs/Python/mlcl/data/headgear