# './configs/configs.yaml'
training:
  batch_size: 128
  lr: 0.0001
  num_epochs: 500
  beta1: 0.5
  ngpu: 1
  seed: 502
  patience: 100
  label_smoothing: False
  gradient_clipping: True
  loss_function: 'BCE' # choose 'BCE' or 'LSGAN'

model:
  image_size: 64 # Spatial size of training images. All images will be resized to this size during preprocessing.
  nc: 3 # Number of channels in the training images. For color images this is 3
  nz: 100 # Size of z latent vector (i.e. size of generator input)
  ngf: 64 # Size of feature maps in generator
  ndf: 64 # Size of feature maps in discriminator
paths:
  annotation: /home/djs/Python/mlcl/data/headgear/headgear.csv
  model_save_path: ./model/dcgan.pth
  dataset_path: /home/djs/Python/mlcl/data/headgear